export const initialProducts = [
    { title: 'Pro Dashboard Template', description: 'A comprehensive dashboard template for professional applications, featuring a wide array of components and charts to visualize data effectively. Built for performance and scalability.', images: ['https://picsum.photos/seed/dash1/800/600', 'https://picsum.photos/seed/dash2/800/600', 'https://picsum.photos/seed/dash3/800/600'], price: 1000.00, category: 'business' },
    { title: 'Creative Website UI Kit', description: 'Modern UI kit for building stunning, responsive websites quickly. Includes a variety of pre-designed components and layouts to kickstart your creative projects and deliver a polished user experience.', images: ['https://picsum.photos/seed/web1/800/600', 'https://picsum.photos/seed/web2/800/600'], price: 2300.00, category: 'corporate' },
    { title: 'E-commerce Software Suite', description: 'All-in-one solution for launching and managing your online store. Features include product management, order tracking, secure payments, and a customizable storefront for a seamless shopping experience.', images: ['https://picsum.photos/seed/ecom1/800/600', 'https://picsum.photos/seed/ecom2/800/600', 'https://picsum.photos/seed/ecom3/800/600'], price: 3500.00, category: 'business' },
    { title: 'Mobile App Template', description: 'A sleek and performant template for iOS and Android apps. Designed with a focus on user experience, it provides a solid foundation for building native-like applications with clean code and modern design.', images: ['https://picsum.photos/seed/app1/800/600', 'https://picsum.photos/seed/app2/800/600'], price: 4000.00, category: 'education' },
    { title: 'Corporate Identity Package', description: 'A complete branding package for corporate clients, including logos, business cards, and marketing materials to establish a strong and consistent brand identity.', images: ['https://picsum.photos/seed/corp1/800/600'], price: 1800.00, category: 'corporate' },
    { title: 'Online Learning Platform', description: 'A fully-featured platform for educational institutions to create and manage online courses, track student progress, and facilitate interactive learning.', images: ['https://picsum.photos/seed/edu1/800/600', 'https://picsum.photos/seed/edu2/800/600'], price: 5200.00, category: 'education' },
    { title: 'SaaS Analytics Platform', description: 'Track user engagement, revenue, and churn with our powerful analytics platform. Integrates with Stripe, Braintree, and more. Customizable dashboards and reports.', images: ['https://picsum.photos/seed/saas1/800/600', 'https://picsum.photos/seed/saas2/800/600'], price: 4999.00, category: 'business' },
    { title: 'Project Management Tool', description: 'Organize tasks, collaborate with your team, and track project progress. Features Kanban boards, Gantt charts, and time tracking to keep your projects on schedule.', images: ['https://picsum.photos/seed/pm1/800/600', 'https://picsum.photos/seed/pm2/800/600', 'https://picsum.photos/seed/pm3/800/600'], price: 1500.00, category: 'corporate' },
    { title: 'Digital Classroom Suite', description: 'An interactive suite for modern education, offering virtual classrooms, assignment management, and collaborative whiteboards for an immersive learning experience.', images: ['https://picsum.photos/seed/digi1/800/600'], price: 3200.00, category: 'education' },
    { title: 'FinTech App UI Kit', description: 'A comprehensive UI kit for building financial technology applications. Includes screens for banking, investments, crypto, and payments, designed for security and ease of use.', images: ['https://picsum.photos/seed/fintech1/800/600', 'https://picsum.photos/seed/fintech2/800/600'], price: 2800.00, category: 'business' },
    { title: 'Corporate Training Module', description: 'Deliver engaging and effective training to your employees. Create custom courses, track completion rates, and issue certifications with our easy-to-use platform.', images: ['https://picsum.photos/seed/training1/800/600'], price: 6000.00, category: 'corporate' },
    { title: 'Language Learning App', description: 'An AI-powered language learning application with interactive lessons, speech recognition, and personalized learning paths to help users master a new language.', images: ['https://picsum.photos/seed/lang1/800/600', 'https://picsum.photos/seed/lang2/800/600'], price: 950.00, category: 'education' },
];
